# SPDX-FileCopyrightText: 2023 froggie <incoming@frogg.ie>
#
# SPDX-License-Identifier: OSL-3.0

blank_issues_enabled: false
contact_links:
  - name: ðŸ“« Email
    url: https://frogg.ie/mailto
    about: Email the developer(s)
  - name: ðŸ“ƒ Discord
    url: https://effectindex.com/discord
    about: Join our Discord for help or to discuss the project
